In [1]:
import numpy as np;

a = np.random.randn(5);

In [2]:
print(a)

[-0.99826248  0.02141927  0.66519194 -1.32456635 -0.17711206]


In [3]:
print(a.shape);

(5,)


In [4]:
print(a.T);

[-0.99826248  0.02141927  0.66519194 -1.32456635 -0.17711206]


In [5]:
print(np.dot(a, a.T));

3.2253117939589986


In [6]:
a = np.random.randn(5,1);
print(a)

[[ 0.73378156]
 [-1.97587504]
 [-0.32346363]
 [ 1.15305912]
 [ 0.09722465]]


In [7]:
print(a.T)

[[ 0.73378156 -1.97587504 -0.32346363  1.15305912  0.09722465]]


In [9]:
print(np.dot(a, a.T));

[[ 0.53843537 -1.44986066 -0.23735165  0.84609352  0.07134165]
 [-1.44986066  3.90408216  0.63912371 -2.27830074 -0.19210376]
 [-0.23735165  0.63912371  0.10462872 -0.37297269 -0.03144864]
 [ 0.84609352 -2.27830074 -0.37297269  1.32954534  0.11210577]
 [ 0.07134165 -0.19210376 -0.03144864  0.11210577  0.00945263]]
